#define Cystck_bf_getbuffer 1
#define Cystck_bf_releasebuffer 2
#define Cystck_mp_ass_subscript 3
#define Cystck_mp_length 4
#define Cystck_mp_subscript 5
#define Cystck_nb_absolute 6
#define Cystck_nb_add 7
#define Cystck_nb_and 8
#define Cystck_nb_bool 9
#define Cystck_nb_divmod 10
#define Cystck_nb_float 11
#define Cystck_nb_floor_divide 12
#define Cystck_nb_index 13
#define Cystck_nb_inplace_add 14
#define Cystck_nb_inplace_and 15
#define Cystck_nb_inplace_floor_divide 16
#define Cystck_nb_inplace_lshift 17
#define Cystck_nb_inplace_multiply 18
#define Cystck_nb_inplace_or 19
#define Cystck_nb_inplace_power 20
#define Cystck_nb_inplace_remainder 21
#define Cystck_nb_inplace_rshift 22
#define Cystck_nb_inplace_subtract 23
#define Cystck_nb_inplace_true_divide 24
#define Cystck_nb_inplace_xor 25
#define Cystck_nb_int 26
#define Cystck_nb_invert 27
#define Cystck_nb_lshift 28
#define Cystck_nb_multiply 29
#define Cystck_nb_negative 30
#define Cystck_nb_or 31
#define Cystck_nb_positive 32
#define Cystck_nb_power 33
#define Cystck_nb_remainder 34
#define Cystck_nb_rshift 35
#define Cystck_nb_subtract 36
#define Cystck_nb_true_divide 37
#define Cystck_nb_xor 38
#define Cystck_sq_ass_item 39
#define Cystck_sq_concat 40
#define Cystck_sq_contains 41
#define Cystck_sq_inplace_concat 42
#define Cystck_sq_inplace_repeat 43
#define Cystck_sq_item 44
#define Cystck_sq_length 45
#define Cystck_sq_repeat 46
#define Cystck_tp_alloc 47
#define Cystck_tp_base 48
#define Cystck_tp_bases 49
#define Cystck_tp_call 50
#define Cystck_tp_clear 51
#define Cystck_tp_dealloc 52
#define Cystck_tp_del 53
#define Cystck_tp_descr_get 54
#define Cystck_tp_descr_set 55
#define Cystck_tp_doc 56
#define Cystck_tp_getattr 57
#define Cystck_tp_getattro 58
#define Cystck_tp_hash 59
#define Cystck_tp_init 60
#define Cystck_tp_is_gc 61
#define Cystck_tp_iter 62
#define Cystck_tp_iternext 63
#define Cystck_tp_methods 64
#define Cystck_tp_new 65
#define Cystck_tp_repr 66
#define Cystck_tp_richcompare 67
#define Cystck_tp_setattr 68
#define Cystck_tp_setattro 69
#define Cystck_tp_str 70
#define Cystck_tp_traverse 71
#define Cystck_tp_members 72
#define Cystck_tp_getset 73
#define Cystck_tp_free 74
#define Cystck_nb_matrix_multiply 75
#define Cystck_nb_inplace_matrix_multiply 76
#define Cystck_am_await 77
#define Cystck_am_aiter 78
#define Cystck_am_anext 79
#define Cystck_tp_finalize 80

